name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install SDL2 dev libs
        run: sudo apt-get install -y --fix-missing libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

      - name: Build
        run: go build -tags headless ./...

      - name: Test
        run: go test -race -tags headless ./...
